# Generated by Django 5.1.4 on 2024-12-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_subjectdb_conames_copoacheiveddata_corelationdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONAMES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.subjectdb', to_field='subject')),
            ],
        ),
    ]
