# Generated by Django 5.1.4 on 2024-12-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_conames'),
    ]

    operations = [
        migrations.AddField(
            model_name='copoacheiveddata',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.adminusers', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='adminusers',
            name='slug',
            field=models.SlugField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='conames',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admin.subjectdb'),
        ),
        migrations.AlterField(
            model_name='corelationdata',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admin.subjectdb'),
        ),
        migrations.DeleteModel(
            name='CourseExitdata',
        ),
    ]
