# Generated by Django 5.1.4 on 2024-12-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_copoacheiveddata_uploaded_by_alter_adminusers_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copoacheiveddata',
            name='copoAch',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='copoacheiveddata',
            name='dataAch',
            field=models.JSONField(null=True),
        ),
    ]
