# Generated by Django 5.1.4 on 2024-12-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_copoacheiveddata_copoach_copoacheiveddata_dataach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conames',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admin.subjectdb', to_field='subject'),
        ),
        migrations.AlterField(
            model_name='corelationdata',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admin.subjectdb', to_field='subject'),
        ),
    ]
