# Generated by Django 5.1.4 on 2024-12-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_conames_subject_alter_corelationdata_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conames',
            name='id',
        ),
        migrations.RemoveField(
            model_name='corelationdata',
            name='id',
        ),
        migrations.AddField(
            model_name='conames',
            name='srno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corelationdata',
            name='srno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
