# Generated by Django 5.1.4 on 2025-01-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_remove_subjectdb_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdb',
            name='new',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
