# Generated by Django 5.1.4 on 2025-01-01 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_subjectdb_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectdb',
            old_name='new',
            new_name='subject_id',
        ),
    ]
