# Generated by Django 5.1.4 on 2025-01-02 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_rename_copo_copoacheiveddata_coursecopoach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copoacheiveddata',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.adminusers'),
        ),
    ]
