# Generated by Django 5.1.4 on 2025-01-04 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_alter_copoacheiveddata_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='copoacheiveddata',
            name='uploade_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
