# Generated by Django 5.1.4 on 2025-01-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_copoacheiveddata_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copoacheiveddata',
            name='batch',
            field=models.CharField(default='FirstName', max_length=10),
        ),
    ]
