# Generated by Django 5.1.4 on 2025-01-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_copoacheiveddata_batch'),
        ('Teachers', '0010_alter_teacher_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='copoacheiveddata',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teachers.branch'),
        ),
    ]
