# Generated by Django 5.1.4 on 2025-01-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_copoacheiveddata_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copoacheiveddata',
            name='id',
        ),
        migrations.AddField(
            model_name='copoacheiveddata',
            name='srno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
