# Generated by Django 5.1.4 on 2025-01-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_remove_copoacheiveddata_id_copoacheiveddata_srno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copoacheiveddata',
            name='srno',
        ),
        migrations.AddField(
            model_name='copoacheiveddata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
