# Generated by Django 5.1.4 on 2025-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0029_remove_copoacheiveddata_srno_copoacheiveddata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='copoacheiveddata',
            name='temp',
            field=models.JSONField(null=True),
        ),
    ]
