# Generated by Django 5.1.4 on 2024-12-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
