# Generated by Django 5.1.4 on 2025-01-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_alter_batch_batch_alter_branch_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject_id',
            field=models.CharField(default='Subject', max_length=20),
        ),
    ]
