# Generated by Django 5.1.4 on 2025-01-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_alter_subjectdb_subject_id'),
        ('Teachers', '0008_teacher_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject_id',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_id_ref', to='Admin.subjectdb', to_field='subject_id'),
        ),
    ]
