# Generated by Django 5.1.4 on 2024-12-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='name@gmail/sies.edu.in', max_length=100)),
                ('usertype', models.CharField(default='TE', max_length=2)),
                ('password', models.CharField(default='Password', max_length=15)),
                ('fname', models.CharField(default='FirstName', max_length=10)),
                ('lname', models.CharField(default='LastName', max_length=10)),
            ],
        ),
    ]
